services:
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ../_data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: carmaint
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 3000:8080

  redis:
    image: redis
    volumes:
      - ../_data/redis:/data

  server:
    build:
      context: ../
      dockerfile: ./build/pkg/app.Dockerfile
    depends_on:
      - redis
      - postgres
    environment:
      - ENV=production
    restart: unless-stopped
    ports:
      - 8080:8080

  frontend:
    build:
      context: ../web
      dockerfile: ../build/pkg/web.Dockerfile
    restart: unless-stopped
    volumes:
     - ../web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8081:80
