services:
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: carmaint
      POSTGRES_PASSWORD: example

  redis:
    image: redis
    volumes:
      - ./data/redis:/data

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - redis
      - postgres
    environment:
      - ENV=production
    restart: unless-stopped
    ports:
      - 8080:8080

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
     - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8081:80