name: Backend Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the backend Docker image
      run: docker build . --file build/pkg/backend.Dockerfile --tag server:$(date +%s)
