name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the frontend Docker image
      run: docker build ./web --file build/pkg/web.Dockerfile --tag frontend:$(date +%s)
